Feature/state machine
berkunal/innit-mate pull request #10
Opened 2022-02-07 19:26 UTC by kcyakici

2022-02-07 19:27 UTC, kcyakici commented
![](https://github.trello.services/images/mini-trello-icon.png) [Finite State Machine Implementation for the Player](https://trello.com/c/lzDYC5Of/73-finite-state-machine-implementation-for-the-player)

2022-02-08 10:33 UTC, berkunal requested changes
Very nice overall, only a few tweaks are needed.

2022-02-08 10:33 UTC, berkunal commented on StateMachine/StateMachine.cs
> +    public override void _Input(InputEvent @event)
We may change this one to _UnhandledInput

2022-02-08 10:33 UTC, berkunal commented on StateMachine/StateMachine.cs
> +            Owner.GetNode<Label>("CurrentState").Text = state;
We can make this label invisible when we are done dealing with the state machine

2022-02-08 10:33 UTC, berkunal commented on StateMachine/State.cs
> +        this.player = (Player)Owner;
leave one space between casted var and the type -> `(Player) Owner`

2022-02-08 10:33 UTC, berkunal commented on Characters/Player/Player.cs
> +    public Vector2 Velocity = new Vector2();
Apply encapsulation to this field also.

2022-02-08 10:33 UTC, berkunal commented on StateMachine/States/Air.cs
> +    public override void handleInput(InputEvent @event)
If you don't have a body you can declare a function in one line: `public override void handleInput(InputEvent @event) { }`

2022-02-08 10:33 UTC, berkunal commented on StateMachine/States/Air.cs
> +        // Apply gravity to the velocity vector
I don't think these comments are needed anymore.

2022-02-08 10:33 UTC, berkunal commented on StateMachine/States/Run.cs
> +        // Update the velocity vector
I don't think these comments are needed anymore.

2022-02-08 10:33 UTC, berkunal commented on StateMachine/States/Idle.cs
> +
Delete empty line

2022-02-08 10:33 UTC, berkunal commented on StateMachine/States/Idle.cs
> +
Delete empty line

2022-02-09 19:19 UTC, berkunal submitted a review, later dismissed

2022-02-09 19:26 UTC, berkunal approved these changes

2022-02-09 19:27 UTC, merged